id: IC0687186
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T20:48:28.139415'
last_modified: '2022-05-30T20:48:28.139421'
parser: null
source_metadata:
  title: Fourth Dodrupchen Rinpoche, Jalü Dorje
  language: zh
  description: 'Texts by and about the Fourth Dodrupchen Rinpoche, Jalü Dorje (''ja''
    lus rdo rje, 1927–1961) alias Rigdzin Tenpe Gyaltsen (rig ''dzin bstan pa''i rgyal
    mtshan):'
  volume:
    fE7AC:
      title: Guru Padmasambhava, Master of the Land of Snows
      base_file: fE7AC.txt
      order: 1
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
